###############################
# 배포/전체 서비스 Docker 실행 용도 #
###############################

# EUREKA --------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

# SPRING --------------------------------------------------
spring:
  jpa:
    hibernate:
      # 운영 안정성 등을 고려하여 배포 또는 테스트환경에서 DB가 변경되지 않고 검증만 하도록 합니다.
      ddl-auto: update

# MONITORING -----------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

  endpoint:
    health:
      show-details: when_authorized

  tracing:
    sampling:
      probability: 0.1 # 운영 환경에서는 트래픽이 많을 수 있으므로 0.1, 0.05등으로 낮추는 것을 검토할 것

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
