spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: cart_user
    password: ${CART_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
