spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cart_db
    username: cart_user
    password: ${CART_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
