spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: company_user
    password: ${COMPANY_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
