spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: payment_user
    password: ${PAYMENT_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
