server:
  port: 19083

spring:
  application:
    name: product-service
  kafka:
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
  elasticsearch:
    uris: ${PRODUCT_ELASTICSEARCH_URIS:http://localhost:9200}
