# SPRING ------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/user_db
    username: user_svc_user
    password: ${USER_DB_PASSWORD}

  jpa:
    show-sql: false
    # user-service는 flyway사용하기때문에 validate 강제
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true # 필요할 때만

# KEYCLOAK -----------------------------------------------------------------
keycloak:
  auth-server-url: http://10.0.10.80:8180

# EUREKA
eureka:
  instance:
    non-secure-port: 19081
