server:
  port: 19081

spring:
  application:
    name: user-service

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    consumer:
      group-id: user-group
      auto-offset-reset: earliest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

keycloak:
  realm: easymeal
  client-id: ${KEYCLOAK_CLIENT_ID:easymeal-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:easymeal-admin}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
